### ISSUE TITLE
What do you do if you have a lot of videos?

### ISSUE THREAD

**Issue by lonngxiang** [ArrowLuo/CLIP4Clip#2]

**Comment by ArrowLuo** [comment]
@lonngxiang It is not a clear question for me. Can you describe clearer? 
I guess your problem is that if there is a lot of videos as retrieval candidates, how to deal with the memory cost. If that is the case, I think the loose type can solve this problem naturally with cached video features. Then the retrieval scores can be calculated via the off-the-shelf feature. Besides, some other hash methods can also be used to speed the retrieval.

**Comment by lonngxiang** [comment]
> @lonngxiang It is not a clear question for me. Can you describe clearer?
> I guess your problem is that if there is a lot of videos as retrieval candidates, how to deal with the memory cost. If that is the case, I think the loose type can solve this problem naturally with cached video features. Then the retrieval scores can be calculated via the off-the-shelf feature. Besides, some other hash methods can also be used to speed the retrieval.

I meaning： A video is divided into many frames of images. Each query is based on image dimension, so the result will be very complicated. I don't know if I can get the video vector directly, so I can directly recall the whole video content that conforms to Query

**Comment by ArrowLuo** [comment]
Yes, we aggregate all frame features via mean pooling, LSTM, Transformer, etc. in our paper. Thus, a video is indeed encoded as a vector. See section 3.3 for more information, please.

**Comment by lonngxiang** [comment]
> Yes, we aggregate all frame features via mean pooling, LSTM, Transformer, etc. in our paper. Thus, a video is indeed encoded as a vector. See section 3.3 for more information, please.

OK, thank you for your patient reply

**Comment by ArrowLuo** [comment]
Thank you for your attention. Reopen this issue if any other questions.

**Comment by lonngxiang** [comment]
use mean pooling, LSTM, Transformer to generate a video vector；Does this paper end up as a similar recall of text vector dot videos vector？
