### ISSUE TITLE
comparison with COOT model

### ISSUE THREAD

**Issue by junchen14** [ArrowLuo/CLIP4Clip#23]
hi,
I am wondering why you don't compare with the COOT model for the activity-net benchmark.
COOT has reported much higher performance with R1 up to 60.8. 

My main concern is that if there is any difference regarding the performance calculation? 

Thanks for your time

**Comment by ArrowLuo** [comment]
Hi @junchen14, we showed the baselines according to the recent work, e.g., several papers this year. The baselines and ours are trained without grounded proposals. I guess the proposals are important to build the relationship between clips of a paragraph and contribute to the feature aggregation. That is also the reason COOT has a high performance than ours and our baselines.  Besides, we use full video as candidates instead of the grounded clips.
