### ISSUE TITLE
max_position_embeddings is wrong for ActivityNet

### ISSUE THREAD

**Issue by GenjiB** [ArrowLuo/CLIP4Clip#31]
max_position_embeddings is set for 77, which is smaller than the summation of max_words and max_frames.

I just change the value of max_position_embeddings to 128. It worked. But, the results of v2t is slightly lower.

Not sure if it is the reason.

**Comment by ArrowLuo** [comment]
Hi @GenjiB, thanks for your question and I have fixed the max_position_embeddings. However, this value will not affect the results due to the bad taste code [here](https://github.com/ArrowLuo/CLIP4Clip/blob/master/modules/modeling.py#L228). I think it is normal for the slight difference in the performance due to the [issue](https://github.com/openai/CLIP/issues/114) besides different hardware.

**Comment by 1240446371** [comment]
> 

hello，do you have the activity net dataset json file  train.json and val_1.json ？can you share them for me?
