### ISSUE TITLE
ActivityNet and DiDeMo dataset!

### ISSUE THREAD

**Issue by haoshuai714** [ArrowLuo/CLIP4Clip#40]
Could you please provide me with the download links of the raw videos of datasets ActivityNet and DiDeMo? (Google cloud link cannot be downloaded in China. Can you open your dataset to baidu Cloud link?)

**Comment by ArrowLuo** [comment]
Hi @haoshuai714, I am afraid that we can not open the raw videos due to the license. But I noticed both ActivityNet and DiDeMo can be downloaded with the Baidu drive and AWS, respectivley.  Check [here](http://activity-net.org/download.html) and [here](https://github.com/LisaAnne/LocalizingMoments) for more information.
