### ISSUE TITLE
MSR-VTT dataset error

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ArrowLuo/CLIP4Clip#44]
when I using MSRVTT dataset, some errors happened, log is "video path: /home/admin/workspace/workgroup/mayiwei.myw/data/MSRVTT/data/MSRVTT/videos/all/video5397.mp4 error. video id:video5397"
![image](https://user-images.githubusercontent.com/33897496/144746365-4e1d80ea-9fb9-4546-9a24-d5859788e9c4.png)
 do you kown what is wrong

**Comment by ArrowLuo** [comment]
Hi @xmu-xiaoma666, this prompt is caused by [this line](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msrvtt_retrieval.py#L286). I think two factors will cause such an error, 1) the video is not found, 2) the video is damaged. If nothing is wrong with the video, a suggestion is to debug the [line](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msrvtt_retrieval.py#L260)  and the RawVideoExtractor itself.

**Comment by shirlyliu** [comment]
I have the same mistakes. Would you finally solve this problem? What's wrong with these videos？The raw_video_data's shape of these videos are [1] causing the error. However, I have tired to make a demo.py to check the wrong videos independently.  The raw_video_data's shape of these videos are more than 3. I have no idea to solve this problem.

**Comment by ArrowLuo** [comment]
Hi @shirlyliu, do you mean your demo.py can extract the right tensor from these wrong videos? If so, a not wise approach is to set `video_path` at [here](https://github.com/ArrowLuo/CLIP4Clip/blob/master/dataloaders/dataloader_msrvtt_retrieval.py#L260) with a wrong video arbitrarily, then print the shape. Maybe something wrong in `awvideo_util.py`.
