### ISSUE TITLE
About batch_size in training configuration?

### ISSUE THREAD

**Issue by xiao2mo** [ArrowLuo/CLIP4Clip#46]
Hi Luo, thanks for your remarkable work!
I am here wondering why use batch 128 in 4gpu DDP training? That is to say 32 per GPU which only accounts for less than 1/2 GPU memory. Is that for some special purpose?

**Comment by ArrowLuo** [comment]
Hi @xiao2mo,  there is no special purpose. We set batch size 32 per GPU because some of our machines are 16G per card, and we need to test some other parameters like frame number. It is an appropriate batch size to finish the hyper-parameters study.  If your card has more than 16G, a suggestion is to test a large frame number, then a  large batch size.

**Comment by xiao2mo** [comment]
I see it. The main problem in my exps is that batch size in DDP configuration may result in different results. Thank u.

**Comment by yumulinfeng1** [comment]
hi
我这边是两张卡，每张卡是16G。
可是我能设置的batchsize是 16， 请问这是为什么呢？

训练配置如下

```
01/10/2022 16:18:00 - INFO -   ***** Running test *****
01/10/2022 16:18:00 - INFO -     Num examples = 497
01/10/2022 16:18:00 - INFO -     Batch size = 16
01/10/2022 16:18:00 - INFO -     Num steps = 32
01/10/2022 16:18:00 - INFO -   ***** Running val *****
01/10/2022 16:18:00 - INFO -     Num examples = 497
222
333
01/10/2022 16:18:12 - INFO -   ***** Running training *****
01/10/2022 16:18:12 - INFO -     Num examples = 130260
01/10/2022 16:18:12 - INFO -     Batch size = 16
01/10/2022 16:18:12 - INFO -     Num steps = 40705
01/10/2022 16:21:34 - INFO -   Epoch: 1/5, Step: 50/8141, Lr: 0.000000001, Loss: 0.455173, Time/step: 4.041784
```


用的资源如图：
![企业微信截图_1641803088178](https://user-images.githubusercontent.com/50360389/148736349-fc3ea454-085c-4a68-a8d7-1164ac169c46.png)
