### ISSUE TITLE
The output of `set(optimizer.get_lr())` is confusing

### ISSUE THREAD

**Issue by HanielF** [ArrowLuo/CLIP4Clip#52]
1. The code of logging at each log_step in latest commit is as follows.
```
                logger.info("Epoch: %d/%s, Step: %d/%d, Lr: %s, Loss: %f, Time/step: %f", epoch + 1,
                            args.epochs, step + 1,
                            len(train_dataloader), "-".join([str('%.9f'%itm) for itm in sorted(list(set(optimizer.get_lr())))]),
                            float(loss),
                            (time.time() - start_time) / (log_step * args.gradient_accumulation_steps))
```
2. The output of `"-".join([str('%.9f'%itm) for itm in sorted(list(set(optimizer.get_lr())))])` in my log is formatted as:
```
2021-12-20 15:12:50,703:INFO: Epoch: 1/5, Step: 10/1406, Lr: 0.000000001, Loss: 1.7373971939086914, Time/step: 15.502562475204467
```
3. While output in others log is formatted as:
```
2021-12-16 13:41:08,839:INFO: Epoch: 1/5, Step: 50/703, Lr: 0.000000014-0.000014225, Loss: 2.009616, Time/step: 15.425273
```
4. Why the column of `Lr` is different and even though i test in latest codebase, it is still only one floating point number.

**Comment by ArrowLuo** [comment]
Hi @HanielF, you may notice there are two parameters, `--lr` and `--coef_lr`, when training the model. We set different learning rates for CLIP and extra modules separately. When using `--sim_header meanP` , there is no extra module except CLIP, so there is only one `Lr: 0.000000001`. Otherwise, there are two learning rates: `Lr: 0.000000014-0.000014225`. 

The `"-".join([str('%.9f'%itm) for itm in sorted(list(set(optimizer.get_lr())))])` is used to see the different learning rates of model.
Thanks.

**Comment by HanielF** [comment]
Thanks very much.
