### ISSUE TITLE
The initialization of seqTransf

### ISSUE THREAD

**Issue by chenyzh28** [ArrowLuo/CLIP4Clip#60]
Hello, thank you for sharing this project.
I try to reproduce the paper results, but I find that on MSR-VTT, the seqTransf is inferior to meanP head. Then I find some problems in the code.
In the paper, the transfomer encoder of seqTransf is initialized by the CLIP's image encoder.
<img width="485" alt="企业微信截图_725a0397-3579-4f00-9964-44d4b0432bb9" src="https://user-images.githubusercontent.com/35193979/154658939-7ecfedc2-ec5b-4832-afdc-296aef4555bd.png">
But in the code, the transfomer encoder of seqTransf is initialized by the CLIP's text encoder.
<img width="911" alt="企业微信截图_d787f313-2580-4410-99be-1b930cebbd6d" src="https://user-images.githubusercontent.com/35193979/154659297-346bf63e-1413-4b8c-8873-f7d78237aec1.png">
Does that problem affect the performance of seqTransf head ?

**Comment by ArrowLuo** [comment]
Hi @chenyzh28, thanks for your question. I think it is a typo in the paper, which should be the text encoder instead of the image encoder due to the dimension of weight. So the code is right. We intuitively suppose that the initialed encoder will benefit the performance with less dataset and did not test more this part.

**Comment by chenyzh28** [comment]
@ArrowLuo, Thanks, I got it.

**Comment by ArrowLuo** [comment]
1.
