### ISSUE TITLE
about the results on MSVD

### ISSUE THREAD

**Issue by yangxiao2** [ArrowLuo/CLIP4Clip#65]
Thanks for your work! When I evaluate the model on MSVD, I find the results of the validation split and the test split are very different, but I can only find the test results in the paper. I'm not sure if I have made some misstakes, can you show the results of the validation split? Thank you very much!

**Comment by ArrowLuo** [comment]
Hi @yangxiao2, sorry that I can not access the history log anymore due to the job change. I also do not have the resources to rerun the experiment on MSVD recently. So I can not provide any numbers. If your results of the test split are comparable with ours, I think you can refer to the other related papers on MSVD to reconsider the difference between test and validation splits. Best.

**Comment by yangxiao2** [comment]
Ok, thanks for your advice! I'll try.

**Comment by reallsp** [comment]
> Thanks for your work! When I evaluate the model on MSVD, I find the results of the validation split and the test split are very different, but I can only find the test results in the paper. I'm not sure if I have made some misstakes, can you show the results of the validation split? Thank you very much!

Hi, I had the same problem as you. My test results on MSVD are as follows,
2022-09-19 13:09:24,078:INFO: Text-to-Video:
2022-09-19 13:09:24,078:INFO:  >>>  R@1: 45.9 - R@5: 75.8 - R@10: 84.7 - Median R: 2.0 - Mean R: 10.2
2022-09-19 13:09:24,078:INFO: Video-to-Text:
2022-09-19 13:09:24,078:INFO:  >>>  V2T$R@1: 46.0 - V2T$R@5: 69.2 - V2T$R@10: 74.5 - V2T$Median R: 2.0 - V2T$Mean R: 13.6
I want to know if your problem is solved. Do I need to adjust the settings of the testing code? Thank you very much.

**Comment by JingXiaolun** [comment]
@reallsp, when I reproduce the meanP results on the MSVD dataset, I encounter similar problem as you. The V2T R@1 can't lead to 56.6 in the paper, and the V2T results at the first epoch is best. The V2T results in subsequent epochs start to decrease.
