### ISSUE TITLE
About Performance

### ISSUE THREAD

**Issue by celestialxevermore** [ArrowLuo/CLIP4Clip#86]
Dear Author, I have a question about the performance result. 

I noticed the several questions about requesting for pre-trained weight.

Seeing these questions, I have supposed that the reason about these people requesting your pre-trained weight is various : time consuming or poor GPU environment than yours, etc.

Here is My Question : 
I think that my question is more related to Deep learning not Clip4clip specifically, 

Q1.
If I get your pre-trained weight of CLIP4clip, It ensures that performance you written in your paper will be driven same?
(Notice that I do not request your pre-trained weight, just question)
Q2.
When I customized your great work in more advanced way for performance 
but not good enough than I expected within a little plus gain, 
Then how can I get 'pre-trained weight **of my own**' like you gained yours from CLIP?
Can it be gained with tremendous epoch? or more large batch size? or any special ideas of yours?
Or should I run 5 epochs and learn again based on the best model from there?
Q3.
I'm curious about the way how you earned your own pre-trained weight. 

Q4. 
There is so many cases about poor performance than the record of T2V retrieval papers.
It result from that the other people who just tried once in their local environment cannot see the same score have no pre-trained weight, which the only participants in the paper have?

Thx always, I 've been questioned and get helped from you several times. I feel really thankful about you.
Sincerely,

**Comment by ArrowLuo** [comment]
Hi @celestialxevermore, thanks for your questions. 
A1: Not sure. The reproducible is nondeterministic. [here](https://github.com/ArrowLuo/CLIP4Clip/issues/63#issuecomment-1064796579). The sure thing is the gap will be small if it exists.
A2: I have no good enough idea about this problem. A suggestion is that you can report your CLIP4Clip's reimplementations besides our results, then you can make a fair comparison in your environment. I think it is a reasonable solution for our community, too. The hyperparameters can be adjusted though we have tested some on them.

Q3 and Q4 are hard for me to understand. But I tried to guess the answers you may want.
A3-4: I guess your problem is also about the reproducible. I must claim that our model is built on CLIP and its pre-trained weight. Our main results (In Tables 1 to 5) in the paper are built on the CLIP's pretrained weight instead of ours. We just fine-tuning the model and evaluation. Our continued pertaining is just an ablation study used to prove that the gain is trivial, so please forget the pretraining in our paper. **Again that the results of Tables 1 to 5 are fine-tuned on the CLIP's pre-trained weight.**

please reply here if there are any problems I do not cover.
Best~

**Comment by celestialxevermore** [comment]
Sorry for my reply and confusing you of my poor english..
I think that you infered my question right, so it made sense. 
By the way, when training your model, is it essential of following this command the below image you mentioned? 
Is it ok without doing this command? I mean, is there any difference in the performance between doing this command or not.
![image](https://user-images.githubusercontent.com/46949994/200126612-e85206ad-5d1c-49f4-8e03-e68df9c027cb.png)

I feel really thankful of you.

**Comment by ArrowLuo** [comment]
@celestialxevermore, Yes, the command is important, which contains some essential hyper-parameters, e.g., batch size and lr. It is suggested to follow our command if it is ok for your computational sources.

**Comment by celestialxevermore** [comment]
Always Thank you. Your reply always helpful for me.
